library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Generated by scripts/gen_descriptors.py -- do not edit by hand.
--
-- USB Audio Class 1.0 playback sink: 384000 Hz, 32-bit, 2 channels, on an
-- isochronous OUT endpoint of 392 bytes per microframe, with an asynchronous
-- feedback endpoint so the host follows the board's audio clock instead of the
-- other way round.  High speed only: this rate does not fit a full-speed frame.
--
-- Total ROM: 177 bytes in a 256-byte memory.

package usb_desc is

    constant DEVICE_OFF : natural := 0;
    constant DEVICE_LEN : natural := 18;
    constant CONFIG_OFF : natural := 18;
    constant CONFIG_LEN : natural := 109;
    constant QUALIFIER_OFF : natural := 127;
    constant QUALIFIER_LEN : natural := 10;
    constant STRING0_OFF : natural := 137;
    constant STRING0_LEN : natural := 4;
    constant STRING1_OFF : natural := 141;
    constant STRING1_LEN : natural := 8;
    constant STRING2_OFF : natural := 149;
    constant STRING2_LEN : natural := 28;

    constant DESC_ADDR_BITS : natural := 8;
    constant EP_AUDIO_OUT   : natural := 1;
    constant EP_FEEDBACK_IN : natural := 1;
    constant AUDIO_MAX_PACKET : natural := 392;

    type desc_rom_t is array (0 to 255) of STD_LOGIC_VECTOR(7 downto 0);

    constant DESC_ROM : desc_rom_t := (
        x"12", x"01", x"00", x"02", x"00", x"00", x"00", x"40",
        x"09", x"12", x"01", x"00", x"00", x"01", x"01", x"02",
        x"00", x"01", x"09", x"02", x"6D", x"00", x"02", x"01",
        x"00", x"80", x"32", x"09", x"04", x"00", x"00", x"00",
        x"01", x"01", x"00", x"00", x"09", x"24", x"01", x"00",
        x"01", x"1E", x"00", x"01", x"01", x"0C", x"24", x"02",
        x"01", x"01", x"01", x"00", x"02", x"03", x"00", x"00",
        x"00", x"09", x"24", x"03", x"03", x"01", x"03", x"00",
        x"01", x"00", x"09", x"04", x"01", x"00", x"00", x"01",
        x"02", x"00", x"00", x"09", x"04", x"01", x"01", x"02",
        x"01", x"02", x"00", x"00", x"07", x"24", x"01", x"01",
        x"01", x"01", x"00", x"0B", x"24", x"02", x"01", x"02",
        x"04", x"20", x"01", x"00", x"DC", x"05", x"09", x"05",
        x"01", x"05", x"88", x"01", x"01", x"00", x"81", x"07",
        x"25", x"01", x"00", x"00", x"00", x"00", x"09", x"05",
        x"81", x"11", x"04", x"00", x"04", x"00", x"00", x"0A",
        x"06", x"00", x"02", x"00", x"00", x"00", x"40", x"01",
        x"00", x"04", x"03", x"09", x"04", x"08", x"03", x"54",
        x"00", x"53", x"00", x"32", x"00", x"1C", x"03", x"54",
        x"00", x"53", x"00", x"32", x"00", x"20", x"00", x"55",
        x"00", x"53", x"00", x"42", x"00", x"20", x"00", x"41",
        x"00", x"75", x"00", x"64", x"00", x"69", x"00", x"6F",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00",
        x"00", x"00", x"00", x"00", x"00", x"00", x"00", x"00"
    );

end package usb_desc;
