library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- The USB subsystem: getting the PHY to clock, the device itself, the audio
-- sink, and the trace that reports on all three.
--
-- Two clock domains meet here.  The reference domain (50 MHz, the board TCXO)
-- owns the PHY's reset and STP pins, measures the PHY's clock output and
-- drives the UART trace; the ULPI domain (60 MHz, generated by the PHY) owns
-- the ULPI bus and everything above it.  The split is deliberate: if the PHY
-- never starts clocking, everything in the ULPI domain is frozen, and the
-- trace still has to come out and say so.
--
-- Nothing about the module's wiring is assumed.  Two things are discovered:
--
--   * Whether the FPGA side works at all.  Once, at startup, the reference
--     domain takes the data bus off the device and drives 0xA5 then 0x5A,
--     reading each back.  That separates a dead I/O bank or a shorted bus from
--     a PHY that simply is not answering.
--
--   * How to make the PHY clock.  The breakout boards label the reset pin
--     "RST" without saying which way round it is, and a ULPI PHY sitting in
--     low power mode also has its clock stopped -- with, confusingly, the same
--     symptom, since ULPI has the PHY assert DIR whenever its clock is not
--     running.  So the search sweeps all four combinations of reset level and
--     STP level and keeps the one that works.  Asserting STP is the spec's way
--     out of low power mode.
--
--     A combination counts as working only when the PHY answers a ULPI
--     register read with the SMSC vendor id.  Clock edges alone are not
--     enough: the USB3300 runs its crystal oscillator and PLL independently of
--     its logic reset, so a part held in reset still drives a perfectly good
--     60 MHz while keeping DIR asserted and answering nothing.  An earlier
--     version of this search locked onto exactly that and sat there.
--
-- Separately from the search, STP is held asserted the whole time the PHY's
-- clock is stopped.  That is the ULPI wake from low power mode, and this part
-- needs it repeatedly rather than once: it stops its clock and asserts DIR
-- whenever it decides there is nothing to do, and without the wake the link
-- can never take the bus back to ask it anything.  Holding STP costs nothing
-- while the clock is down, because with no clock the link cannot be
-- transmitting anyway, and it is released within microseconds of the clock
-- restarting.
--
--     A third possibility, a PHY strapped for input clock mode that expects
--     the link to supply the 60 MHz, cannot be tested from here any more:
--     ulpi_clk is on PIN_23, a dedicated clock input, which the device can
--     only read.  It was tested while the pin was on PIN_50 and the PHY stayed
--     silent through all four reset and STP combinations with the FPGA driving
--     a measured 60.00 MHz, so nothing is lost.  Putting the wire back on
--     PIN_50 and making the port bidirectional would restore it.
--
-- The sweep runs forever until something works and restarts if it ever stops
-- working, so a module powered up after configuration recovers by itself.
--
-- Once the PHY is running, a device that the host has not configured within a
-- few seconds is detached and re-attached by pulsing the PHY reset, which
-- drops TermSelect and so the D+ pull-up.  A host that has given up on a port
-- will not retry on its own -- it disables it until something physically
-- changes -- so without this, one failed enumeration means power-cycling the
-- board to get another attempt.
--
-- Status frame, emitted every ~200 ms at 1 Mbaud, decoded by
-- debug/usb_trace.py.  Values from the ULPI domain are snapshotted there on
-- request and read back a whole frame later, so nothing in the frame is a
-- torn multi-byte counter.
--
--    0  0x55            magic
--    1  0xAA
--    2  live rate lo    PHY clock edges in the last 100 ms window, /128
--    3  live rate hi
--    4  combo 0 lo      same count with RST=0, STP=0
--    5  combo 0 hi
--    6  combo 1 lo      RST=0, STP=1
--    7  combo 1 hi
--    8  combo 2 lo      RST=1, STP=0
--    9  combo 2 hi
--   10  combo 3 lo      RST=1, STP=1
--   11  combo 3 hi
--   12  flags           bit0 reset run level, bit1 PHY released, bit2 vendor
--                       id matched, bit3 clock ever seen, bits 5:4 combo now
--                       under test
--   13  usb flags       bit0 PHY configured, bit1 device configured, bit2
--                       streaming, bit3 audio playing, bits 5:4 line state,
--                       bit6 a USB reset has been seen
--   14  device address
--   15  frame number lo
--   16  frame number hi
--   17  SOF count lo    start-of-frames in the last 100 ms window, expect 100
--   18  SOF count hi
--   19  audio packets lo   good isochronous packets in the last window
--   20  audio packets hi
--   21  audio packets dropped, running total
--   22  FIFO overflows, running total
--   23  FIFO underruns, running total
--   24  feedback rate byte 0    16.16 samples per microframe,
--   25  feedback rate byte 1    0x00300000 = 48.000
--   26  feedback rate byte 2
--   27  heartbeat
--   28  pin level   DATA[7:0]
--   29  pin level   bit0 CLK, bit1 DIR, bit2 NXT
--   30  pin toggled DATA[7:0], set if the pin changed during the last window
--   31  pin toggled bit0 CLK, bit1 DIR, bit2 NXT
--   32  bus readback with DATA driven to 0xA5
--   33  bus readback with DATA driven to 0x5A
--   34  probe bits      one per reset/STP combination, set if the PHY
--                       answered the vendor id read in that trial
--   35  vendor id byte as actually read back, expect 0x24
--   36  how far the PHY setup sequence got, 0..11
--   37  function control read back, expect 0x45
--   38  otg control read back, expect 0x00
--   39  line status straight from the PHY, not the snapshot: [1:0] line
--       state, [3:2] VBUS
--   40  product id low read back, expect 0x07
--   41  scratch register read back after writing 0xFF
--   42  the same after writing 0x55
--   43  the same after writing 0xAA
--   44  search state in bits 7:5 and, in bits 4:0, how many windows the
--       device has been locked but unconfigured
--   45  audio FIFO overflows, running total
--   46  audio FIFO underruns, running total
--   47  feedback rate byte 3
--   48  completed high-speed chirp handshakes
--
-- Each status frame is followed by a bus capture block: the two bytes
-- 0x55 0xBB, then 1024 entries of four bytes each -- the bus byte, then bit0
-- DIR, bit1 NXT, bit2 STP, bit3 link driving, then how many cycles that state
-- lasted as a 16-bit count.  See ulpi_capture.vhd.

entity usb_top is
    Generic (
        -- Reference clock cycles per UART bit: 50 MHz / 1 Mbaud.
        UART_DIV : natural := 50
    );
    Port (
        clk_ref  : in    STD_LOGIC;   -- 50 MHz board reference

        -- The PHY's 60 MHz, on a dedicated clock input.
        ulpi_clk : in    STD_LOGIC;
        ulpi_d   : inout STD_LOGIC_VECTOR(7 downto 0);
        ulpi_dir : in    STD_LOGIC;
        ulpi_nxt : in    STD_LOGIC;
        ulpi_stp : out   STD_LOGIC;
        ulpi_rst : out   STD_LOGIC;

        uart_tx  : out   STD_LOGIC;

        -- Audio side, in the I2S clock domain.
        aclk       : in  STD_LOGIC;
        frame_tick : in  STD_LOGIC;
        sample_l   : out signed(31 downto 0);
        sample_r   : out signed(31 downto 0);
        -- High while USB audio is what the DAC is being fed.
        audio_active : out STD_LOGIC
    );
end usb_top;

architecture Behavioral of usb_top is

    ------------------------------------------------------------------
    -- Reference domain
    ------------------------------------------------------------------
    constant WINDOW    : natural := 5_000_000;    -- 100 ms at 50 MHz
    constant FRAME_GAP : natural := 10_000_000;   -- 200 ms between frames
    -- 60 MHz through the /128 witness is 46875 counts in a window; anything
    -- above a few hundred means a clock is genuinely running.
    constant CLK_ALIVE : natural := 1000;

    signal win_cnt  : unsigned(22 downto 0) := (others => '0');
    signal win_tick : STD_LOGIC := '0';

    -- The ULPI domain toggles a bit every 128 of its clocks; counting the
    -- toggles here measures the PHY clock without needing it to be running.
    signal ulpi_div : unsigned(7 downto 0) := (others => '0');
    signal ulpi_tgl : STD_LOGIC := '0';
    signal tgl_s1, tgl_s2, tgl_s3 : STD_LOGIC := '0';
    signal tick_cnt  : unsigned(15 downto 0) := (others => '0');
    signal ulpi_rate : unsigned(15 downto 0) := (others => '0');

    -- A live 60 MHz clock moves the witness every 2.1 us, so 10 us of
    -- stillness means it has stopped.  This is deliberately far quicker than
    -- the 100 ms measurement window: it drives the STP wake, which wants to
    -- react immediately rather than at the end of a window.
    signal clk_idle : unsigned(9 downto 0) := (others => '0');
    signal clk_dead : STD_LOGIC := '1';

    type srch_t is (T_A5, T_A5_MEAS, T_5A, T_5A_MEAS, T_TRY, T_MEAS, T_LOCKED,
                    T_DETACH);
    signal srch  : srch_t := T_A5;
    signal combo : unsigned(1 downto 0) := (others => '0');

    type cnt_t is array (0 to 3) of unsigned(15 downto 0);
    signal counts : cnt_t := (others => (others => '0'));
    signal probes : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');

    signal run_level  : STD_LOGIC := '0';
    signal rst_pin    : STD_LOGIC := '0';
    signal stp_force  : STD_LOGIC := '0';
    signal phy_go     : STD_LOGIC := '0';
    signal clock_seen : STD_LOGIC := '0';

    -- Pin census, sampled in the reference domain so it still works with the
    -- PHY clock stopped.  "toggled" is sticky over one measurement window.
    signal pin_s1, pin_s2, pin_prev : STD_LOGIC_VECTOR(10 downto 0) := (others => '0');
    signal pin_tog, pin_tog_lat     : STD_LOGIC_VECTOR(10 downto 0) := (others => '0');

    -- Connectivity test: the reference domain borrows the data bus before the
    -- PHY is allowed to run.
    signal test_oe   : STD_LOGIC := '0';
    signal test_data : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal read_a5   : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal read_5a   : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');

    signal frame_cnt : unsigned(23 downto 0) := (others => '0');
    -- Wide enough for the status frame plus the 1024-byte capture block.
    signal frame_idx : unsigned(12 downto 0) := (others => '1');
    constant CAP_START : natural := 51;
    constant FRAME_END : natural := CAP_START + 4095;
    signal heartbeat : unsigned(7 downto 0)  := (others => '0');
    signal tx_byte   : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal tx_valid  : STD_LOGIC := '0';
    signal tx_ready  : STD_LOGIC;

    ------------------------------------------------------------------
    -- ULPI domain
    ------------------------------------------------------------------
    signal usb_rst : STD_LOGIC;
    signal m_dout  : STD_LOGIC_VECTOR(7 downto 0);
    signal m_oe    : STD_LOGIC;
    signal m_stp   : STD_LOGIC;

    signal phy_ready, phy_id_ok, usb_reset, configured, streaming : STD_LOGIC;
    signal speed_hs : STD_LOGIC;
    signal chirps   : unsigned(7 downto 0);
    signal dev_addr  : STD_LOGIC_VECTOR(6 downto 0);
    signal sof       : STD_LOGIC;
    signal frame_no  : STD_LOGIC_VECTOR(10 downto 0);
    signal linestate : STD_LOGIC_VECTOR(1 downto 0);

    signal audio_data  : STD_LOGIC_VECTOR(7 downto 0);
    signal audio_valid : STD_LOGIC;
    signal audio_done  : STD_LOGIC;
    signal audio_drop  : STD_LOGIC;
    signal fb_value    : unsigned(31 downto 0);
    signal stat_setup, stat_tx : unsigned(7 downto 0);
    signal stat_over, stat_under : unsigned(7 downto 0);

    signal sof_cnt,  sof_win  : unsigned(15 downto 0) := (others => '0');
    signal pkt_cnt,  pkt_win  : unsigned(15 downto 0) := (others => '0');
    signal drop_cnt : unsigned(7 downto 0) := (others => '0');
    signal reset_seen : STD_LOGIC := '0';

    -- Snapshot handshake.  The reference domain flips snap_req once per trace
    -- frame; the ULPI domain copies its counters into snap_* on seeing it, and
    -- they are then static for the whole 200 ms before the frame goes out, so
    -- a plain resynchroniser cannot catch one mid-change.
    signal snap_req : STD_LOGIC := '0';
    signal req_s1, req_s2, req_s3 : STD_LOGIC := '0';
    signal snap_flags : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal snap_addr  : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal snap_frame : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal snap_sof   : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal snap_pkt   : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal snap_misc  : STD_LOGIC_VECTOR(23 downto 0) := (others => '0');
    signal snap_fb    : STD_LOGIC_VECTOR(31 downto 0) := (others => '0');
    signal snap_fifo  : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal snap_chirp : STD_LOGIC_VECTOR(7 downto 0)  := (others => '0');
    signal phy_vid    : STD_LOGIC_VECTOR(7 downto 0);
    signal init_step  : STD_LOGIC_VECTOR(3 downto 0);
    signal phy_pid    : STD_LOGIC_VECTOR(7 downto 0);
    signal scr_ff     : STD_LOGIC_VECTOR(7 downto 0);
    signal scr_55     : STD_LOGIC_VECTOR(7 downto 0);
    signal scr_aa     : STD_LOGIC_VECTOR(7 downto 0);
    signal reg_func   : STD_LOGIC_VECTOR(7 downto 0);
    signal reg_otg    : STD_LOGIC_VECTOR(7 downto 0);
    signal vbus       : STD_LOGIC_VECTOR(1 downto 0);
    signal r_vid      : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_func     : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_otg      : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_vbus     : STD_LOGIC_VECTOR(1 downto 0) := (others => '0');
    signal r_line     : STD_LOGIC_VECTOR(1 downto 0) := (others => '0');
    signal r_pid      : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_sff      : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_s55      : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_saa      : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_step     : STD_LOGIC_VECTOR(3 downto 0) := (others => '0');

    signal r_flags : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_addr  : STD_LOGIC_VECTOR(7 downto 0) := (others => '0');
    signal r_frame : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal r_sof   : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal r_pkt   : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal r_misc  : STD_LOGIC_VECTOR(23 downto 0) := (others => '0');
    signal r_fb    : STD_LOGIC_VECTOR(31 downto 0) := (others => '0');
    signal r_fifo  : STD_LOGIC_VECTOR(15 downto 0) := (others => '0');
    signal r_chirp : STD_LOGIC_VECTOR(7 downto 0)  := (others => '0');

    signal cap_addr : unsigned(9 downto 0);
    signal cap_byte : unsigned(1 downto 0);
    signal cap_data : STD_LOGIC_VECTOR(31 downto 0);
    signal cap_full : STD_LOGIC;

    signal act_a, act_s1, act_s2 : STD_LOGIC := '0';
    signal owns_dac : STD_LOGIC;
    signal id_s1, id_s2 : STD_LOGIC := '0';
    signal cfg_s1, cfg_s2 : STD_LOGIC := '0';
    -- Windows spent locked but unconfigured, before giving the host another
    -- chance.  30 windows is 3 s, comfortably longer than an enumeration.
    signal idle_win : unsigned(5 downto 0) := (others => '0');
    signal srch_code : STD_LOGIC_VECTOR(2 downto 0);

begin

    ulpi_rst <= rst_pin;
    -- Either the search is driving STP for a trial, or the PHY has stopped
    -- clocking and needs waking.
    ulpi_stp <= '1' when (stp_force = '1' or clk_dead = '1') else m_stp;

    -- The connectivity test outranks the device, which otherwise drives the
    -- idle command byte whenever the PHY is not using the bus.
    ulpi_d <= test_data when test_oe = '1' else
              m_dout    when m_oe = '1' else
              (others => 'Z');

    -- Held in reset until the search has settled on something that clocks.
    usb_rst <= not phy_go;

    device : entity work.usb_device
        port map (
            clk         => ulpi_clk,
            rst         => usb_rst,
            d_in        => ulpi_d,
            d_out       => m_dout,
            d_oe        => m_oe,
            ulpi_dir    => ulpi_dir,
            ulpi_nxt    => ulpi_nxt,
            ulpi_stp    => m_stp,
            phy_ready   => phy_ready,
            speed_hs    => speed_hs,
            chirps      => chirps,
            phy_id_ok   => phy_id_ok,
            phy_vid     => phy_vid,
            phy_pid     => phy_pid,
            scr_ff      => scr_ff,
            scr_55      => scr_55,
            scr_aa      => scr_aa,
            reg_func    => reg_func,
            reg_otg     => reg_otg,
            vbus        => vbus,
            init_step   => init_step,
            usb_reset   => usb_reset,
            configured  => configured,
            streaming   => streaming,
            dev_addr    => dev_addr,
            sof         => sof,
            frame_no    => frame_no,
            linestate   => linestate,
            audio_data  => audio_data,
            audio_valid => audio_valid,
            audio_done  => audio_done,
            audio_drop  => audio_drop,
            stat_setup  => stat_setup,
            stat_tx     => stat_tx,
            fb_value    => fb_value
        );

    sink : entity work.usb_audio
        port map (
            usb_clk     => ulpi_clk,
            rst         => usb_rst,
            streaming   => streaming,
            sof         => sof,
            audio_data  => audio_data,
            audio_valid => audio_valid,
            audio_done  => audio_done,
            audio_drop  => audio_drop,
            fb_value    => fb_value,
            stat_over   => stat_over,
            stat_under  => stat_under,
            aclk        => aclk,
            frame_tick  => frame_tick,
            sample_l    => sample_l,
            sample_r    => sample_r,
            active      => act_a,
            owns_dac    => owns_dac
        );

    audio_active <= owns_dac;

    -- The address is driven a whole UART byte time ahead of the byte that
    -- uses it, so the memory's registered output has long since settled.
    cap_addr <= resize((frame_idx - CAP_START) srl 2, 10);
    -- Which byte of the four-byte entry.  Taken from the offset into the
    -- block, not from frame_idx itself, so moving the block does not silently
    -- rotate every entry.
    cap_byte <= resize(frame_idx - CAP_START, 2);

    capture : entity work.ulpi_capture
        -- 0x2D is a SETUP token's PID with its check nibble, so the capture
        -- covers a whole control transfer from its first packet.
        generic map (TRIGGER => x"2D")
        port map (
            clk     => ulpi_clk,
            arm     => phy_go,
            d       => ulpi_d,
            dir     => ulpi_dir,
            nxt     => ulpi_nxt,
            stp     => m_stp,
            oe      => m_oe,
            rd_clk  => clk_ref,
            rd_addr => cap_addr,
            rd_data => cap_data,
            full    => cap_full
        );

    ------------------------------------------------------------------
    -- ULPI domain: clock witness, activity counters and the snapshot
    ------------------------------------------------------------------
    process(ulpi_clk)
    begin
        if rising_edge(ulpi_clk) then
            ulpi_div <= ulpi_div + 1;
            if ulpi_div = 127 then
                ulpi_div <= (others => '0');
                ulpi_tgl <= not ulpi_tgl;
            end if;

            if sof = '1' then
                sof_cnt <= sof_cnt + 1;
            end if;
            if audio_done = '1' then
                pkt_cnt <= pkt_cnt + 1;
            end if;
            if audio_drop = '1' then
                drop_cnt <= drop_cnt + 1;
            end if;
            if usb_reset = '1' then
                reset_seen <= '1';
            end if;

            req_s1 <= snap_req;
            req_s2 <= req_s1;
            req_s3 <= req_s2;
            if req_s3 /= req_s2 then
                -- The two rate counters are reported per window and restart
                -- here; the rest are levels or running totals.
                snap_flags <= speed_hs & reset_seen & linestate & act_s2 &
                              streaming & configured & phy_ready;
                snap_chirp <= std_logic_vector(chirps);
                snap_addr  <= '0' & dev_addr;
                snap_frame <= "00000" & frame_no;
                snap_sof   <= std_logic_vector(sof_cnt);
                snap_pkt   <= std_logic_vector(pkt_cnt);
                -- Setup packets accepted and packets transmitted say, in one
                -- glance, whether the device is hearing the host and whether
                -- it is answering.
                snap_misc  <= std_logic_vector(stat_tx) &
                              std_logic_vector(stat_setup) &
                              std_logic_vector(drop_cnt);
                snap_fb    <= std_logic_vector(fb_value);
                snap_fifo  <= std_logic_vector(stat_under) &
                              std_logic_vector(stat_over);
                sof_cnt    <= (others => '0');
                pkt_cnt    <= (others => '0');
            end if;

            -- The audio sink's "playing" flag lives in the I2S domain.
            act_s1 <= act_a;
            act_s2 <= act_s1;

            if usb_rst = '1' then
                sof_cnt    <= (others => '0');
                pkt_cnt    <= (others => '0');
                drop_cnt   <= (others => '0');
                reset_seen <= '0';
            end if;
        end if;
    end process;

    ------------------------------------------------------------------
    -- Reference domain
    ------------------------------------------------------------------
    process(clk_ref)
    begin
        if rising_edge(clk_ref) then

            -- Two stages before use; these pins are asynchronous to this
            -- clock by definition.
            pin_s1   <= ulpi_nxt & ulpi_dir & ulpi_clk & ulpi_d;
            pin_s2   <= pin_s1;
            pin_prev <= pin_s2;
            if pin_s2 /= pin_prev then
                pin_tog <= pin_tog or (pin_s2 xor pin_prev);
            end if;

            tgl_s1 <= ulpi_tgl;
            tgl_s2 <= tgl_s1;
            tgl_s3 <= tgl_s2;

            if tgl_s3 /= tgl_s2 then
                clk_idle <= (others => '0');
                clk_dead <= '0';
            elsif clk_idle = 500 then           -- 10 us at 50 MHz
                clk_dead <= '1';
            else
                clk_idle <= clk_idle + 1;
            end if;

            id_s1  <= phy_id_ok;
            id_s2  <= id_s1;
            cfg_s1 <= configured;
            cfg_s2 <= cfg_s1;
            -- Static except when a trial changes it, so one stage is enough.
            r_vid  <= phy_vid;
            r_pid  <= phy_pid;
            r_sff  <= scr_ff;
            r_s55  <= scr_55;
            r_saa  <= scr_aa;
            r_func <= reg_func;
            r_otg  <= reg_otg;
            r_vbus <= vbus;
            r_line <= linestate;
            r_step <= init_step;

            -- Snapshot registers are static between requests, so one
            -- resynchronising stage each is enough.
            r_flags <= snap_flags;
            r_addr  <= snap_addr;
            r_frame <= snap_frame;
            r_sof   <= snap_sof;
            r_pkt   <= snap_pkt;
            r_misc  <= snap_misc;
            r_fb    <= snap_fb;
            r_fifo  <= snap_fifo;
            r_chirp <= snap_chirp;

            win_tick <= '0';
            if win_cnt = WINDOW - 1 then
                win_cnt     <= (others => '0');
                win_tick    <= '1';
                ulpi_rate   <= tick_cnt;
                tick_cnt    <= (others => '0');
                pin_tog_lat <= pin_tog;
                pin_tog     <= (others => '0');
            else
                win_cnt <= win_cnt + 1;
                if tgl_s3 /= tgl_s2 then
                    tick_cnt <= tick_cnt + 1;
                end if;
            end if;

            ----------------------------------------------------------
            -- Startup census, then the clock search
            ----------------------------------------------------------
            case srch is

                -- Drive the bus with two complementary patterns and read each
                -- back a window later, once it has been through the
                -- resynchroniser.
                when T_A5 =>
                    test_oe   <= '1';
                    test_data <= x"A5";
                    if win_tick = '1' then
                        srch <= T_A5_MEAS;
                    end if;

                when T_A5_MEAS =>
                    if win_tick = '1' then
                        read_a5   <= pin_s2(7 downto 0);
                        test_data <= x"5A";
                        srch      <= T_5A;
                    end if;

                when T_5A =>
                    if win_tick = '1' then
                        srch <= T_5A_MEAS;
                    end if;

                when T_5A_MEAS =>
                    if win_tick = '1' then
                        read_5a <= pin_s2(7 downto 0);
                        test_oe <= '0';
                        srch    <= T_TRY;
                    end if;

                -- Settle window: apply the combination.  STP is only held
                -- during this window, which is exactly the shape of the ULPI
                -- low power wake -- assert STP, wait for the clock, release --
                -- and leaves the pin free for the device afterwards.
                when T_TRY =>
                    rst_pin   <= combo(1);
                    stp_force <= combo(0);
                    phy_go    <= '0';
                    if win_tick = '1' then
                        srch <= T_MEAS;
                    end if;

                -- Measurement window, with STP released so a PHY that has just
                -- woken is free to use the bus, and the device let go so it
                -- can try to read the vendor id.  A whole window is far more
                -- than the millisecond of settling plus three register cycles
                -- that takes.
                when T_MEAS =>
                    stp_force <= '0';
                    phy_go    <= '1';
                    if win_tick = '1' then
                        counts(to_integer(combo)) <= ulpi_rate;
                        probes(to_integer(combo)) <= id_s2;
                        -- The vendor id coming back is proof enough that the
                        -- clock ran: the register read cannot complete without
                        -- it.  The edge count is only reported, not tested,
                        -- because the PHY does not necessarily clock for the
                        -- whole window -- it starts when the reset is released
                        -- part way in.
                        if id_s2 = '1' then
                            run_level  <= combo(1);
                            clock_seen <= '1';
                            srch       <= T_LOCKED;
                        else
                            combo <= combo + 1;
                            srch  <= T_TRY;
                        end if;
                    end if;

                when T_LOCKED =>
                    rst_pin   <= run_level;
                    stp_force <= '0';
                    phy_go    <= '1';
                    if win_tick = '1' then
                        -- If the PHY ever stops answering, start hunting again
                        -- rather than sitting there dead.
                        if id_s2 = '0' then
                            phy_go   <= '0';
                            combo    <= (others => '0');
                            idle_win <= (others => '0');
                            srch     <= T_TRY;
                        elsif cfg_s2 = '1' then
                            idle_win <= (others => '0');
                        elsif idle_win = 30 then
                            idle_win <= (others => '0');
                            phy_go   <= '0';
                            srch     <= T_DETACH;
                        else
                            idle_win <= idle_win + 1;
                        end if;
                    end if;

                -- Hold the PHY in reset for a window.  That clears its
                -- registers, so TermSelect and the D+ pull-up go with them and
                -- the host sees a genuine disconnect; coming back out of
                -- reset re-runs the setup sequence and re-attaches.
                when T_DETACH =>
                    rst_pin <= not run_level;
                    phy_go  <= '0';
                    if win_tick = '1' then
                        srch <= T_LOCKED;
                    end if;

            end case;

            ----------------------------------------------------------
            -- Status frame
            ----------------------------------------------------------
            if tx_valid = '1' and tx_ready = '1' then
                tx_valid <= '0';
            end if;

            if frame_idx > FRAME_END then
                if frame_cnt = FRAME_GAP - 1 then
                    frame_cnt <= (others => '0');
                    frame_idx <= (others => '0');
                    heartbeat <= heartbeat + 1;
                else
                    frame_cnt <= frame_cnt + 1;
                    -- Ask for a fresh snapshot as soon as the last frame has
                    -- gone, leaving the whole gap for it to settle.
                    if frame_cnt = 0 then
                        snap_req <= not snap_req;
                    end if;
                end if;
            elsif tx_valid = '0' and tx_ready = '1' then
                tx_valid  <= '1';
                frame_idx <= frame_idx + 1;
                case to_integer(frame_idx) is
                    when  0 => tx_byte <= x"55";
                    when  1 => tx_byte <= x"AA";
                    when  2 => tx_byte <= std_logic_vector(ulpi_rate(7 downto 0));
                    when  3 => tx_byte <= std_logic_vector(ulpi_rate(15 downto 8));
                    when  4 => tx_byte <= std_logic_vector(counts(0)(7 downto 0));
                    when  5 => tx_byte <= std_logic_vector(counts(0)(15 downto 8));
                    when  6 => tx_byte <= std_logic_vector(counts(1)(7 downto 0));
                    when  7 => tx_byte <= std_logic_vector(counts(1)(15 downto 8));
                    when  8 => tx_byte <= std_logic_vector(counts(2)(7 downto 0));
                    when  9 => tx_byte <= std_logic_vector(counts(2)(15 downto 8));
                    when 10 => tx_byte <= std_logic_vector(counts(3)(7 downto 0));
                    when 11 => tx_byte <= std_logic_vector(counts(3)(15 downto 8));
                    when 12 => tx_byte <= "00" & std_logic_vector(combo) &
                                          clock_seen & id_s2 & phy_go & run_level;
                    when 13 => tx_byte <= r_flags;
                    when 14 => tx_byte <= r_addr;
                    when 15 => tx_byte <= r_frame(7 downto 0);
                    when 16 => tx_byte <= r_frame(15 downto 8);
                    when 17 => tx_byte <= r_sof(7 downto 0);
                    when 18 => tx_byte <= r_sof(15 downto 8);
                    when 19 => tx_byte <= r_pkt(7 downto 0);
                    when 20 => tx_byte <= r_pkt(15 downto 8);
                    when 21 => tx_byte <= r_misc(7 downto 0);
                    when 22 => tx_byte <= r_misc(15 downto 8);
                    when 23 => tx_byte <= r_misc(23 downto 16);
                    when 24 => tx_byte <= r_fb(7 downto 0);
                    when 25 => tx_byte <= r_fb(15 downto 8);
                    when 26 => tx_byte <= r_fb(23 downto 16);
                    when 27 => tx_byte <= std_logic_vector(heartbeat);
                    when 28 => tx_byte <= pin_s2(7 downto 0);
                    when 29 => tx_byte <= "00000" & pin_s2(10 downto 8);
                    when 30 => tx_byte <= pin_tog_lat(7 downto 0);
                    when 31 => tx_byte <= "00000" & pin_tog_lat(10 downto 8);
                    when 32 => tx_byte <= read_a5;
                    when 33 => tx_byte <= read_5a;
                    when 34 => tx_byte <= x"0" & probes;
                    when 35 => tx_byte <= r_vid;
                    when 36 => tx_byte <= "0000" & r_step;
                    when 37 => tx_byte <= r_func;
                    when 38 => tx_byte <= r_otg;
                    when 39 => tx_byte <= x"0" & r_vbus & r_line;
                    when 40 => tx_byte <= r_pid;
                    when 41 => tx_byte <= r_sff;
                    when 42 => tx_byte <= r_s55;
                    when 43 => tx_byte <= r_saa;
                    when 44 => tx_byte <= srch_code & std_logic_vector(idle_win(4 downto 0));
                    when 45 => tx_byte <= r_fifo(7 downto 0);
                    when 46 => tx_byte <= r_fifo(15 downto 8);
                    when 47 => tx_byte <= r_fb(31 downto 24);
                    when 48 => tx_byte <= r_chirp;
                    when 49 => tx_byte <= x"55";
                    when 50 => tx_byte <= x"BB";
                    when others =>
                        -- The capture block: bus byte, control byte, then the
                        -- dwell count low and high.
                        case to_integer(cap_byte) is
                            when 0      => tx_byte <= cap_data(7 downto 0);
                            when 1      => tx_byte <= cap_data(15 downto 8);
                            when 2      => tx_byte <= cap_data(23 downto 16);
                            when others => tx_byte <= cap_data(31 downto 24);
                        end case;
                end case;
            end if;

        end if;
    end process;

    with srch select srch_code <=
        "000" when T_A5,      "001" when T_A5_MEAS,
        "010" when T_5A,      "011" when T_5A_MEAS,
        "100" when T_TRY,     "101" when T_MEAS,
        "110" when T_LOCKED,  "111" when others;

    uart : entity work.uart_tx
        generic map (DIVISOR => UART_DIV)
        port map (
            clk   => clk_ref,
            data  => tx_byte,
            valid => tx_valid,
            ready => tx_ready,
            tx    => uart_tx
        );

end Behavioral;
